let stockProductos = [
    {id: 1, nombre: "labial 1", tipo: "labial", cantidad: 1, desc: "Un labial que  va con vos", precio: 5.29, talle: "L", img: './img/labial1.png'},
    {id: 2, nombre: "labial 2", tipo: "labial", cantidad: 1, desc: "Un labial que va con vos", precio: 5.29, talle: "L", img: './img/labial2.png'},
    {id: 3, nombre: "labial 3", tipo: "labial", cantidad: 1, desc: "Un labial que  va con vos", precio: 5.29, talle: "M", img: './img/labial3.png'},
    {id: 4, nombre: "labial 4", tipo: "labial", cantidad: 1, desc: "Un labial que  va con vos", precio: 5.29, talle: "M", img: './img/labial04.png'},
    {id: 5, nombre: "labial 5", tipo: "labial", cantidad: 1, desc: "Un labial que  va con vos", precio: 5.29, talle: "S", img: './img/labial06.png'},
    {id: 6, nombre: "labial 6", tipo: "labial", cantidad: 1, desc: "Un labial que  va con vos", precio: 5.29, talle: "S", img: './img/labial108.png'},
    {id: 7, nombre: "base 1", tipo: "base", cantidad: 1, desc: "Una base que  va con vos", precio: 5.29, talle: "L", img: './img/base01.png'},
    {id: 8, nombre: "base 2", tipo: "base", cantidad: 1, desc: "Una base que  va con vos", precio: 5.29, talle: "L", img: './img/base01.png'},
    {id: 9, nombre: "base 3", tipo: "base", cantidad: 1, desc: "Una base que  va con vos", precio: 5.29, talle: "M", img: './img/base02.png'},
    {id: 10, nombre: "base 4", tipo: "base", cantidad: 1, desc: "Una base que  va con vos", precio: 5.29, talle: "M", img: './img/base03.png'},
    {id: 11, nombre: "base 5", tipo: "base", cantidad: 1,desc: "Una base que  va con vos", precio: 5.29, talle: "S", img: './img/base05.png'},
    {id: 12, nombre: "base 6", tipo: "base", cantidad: 1, desc: "Una base que  va con vos", precio: 5.29, talle: "S", img: './img/base06.png'},
    {id: 13, nombre: "sombras 1", tipo: "sombras", cantidad: 1, desc: "Una sombra que  va con vos", precio: 5.29, talle: "L", img: './img/tonners.jpg'},
    {id: 14, nombre: "sombras 2", tipo: "sombras", cantidad: 1, desc: "Una sombra que  va con vos", precio: 5.29, talle: "S", img: './img/20011777-01.png'},
    {id: 15, nombre: "sombras 3", tipo: "sombras", cantidad: 1, desc: "Una sombra que va con vos", precio: 5.29, talle: "L", img: './img/20011777-02.png'},
    {id: 16, nombre: "sombras 4", tipo: "sombras", cantidad: 1, desc: "Una sombra que  va con vos", precio: 5.29, talle: "S", img: './img/20011777-03.png'},
    {id: 17, nombre: "sombras 5", tipo: "sombras", cantidad: 1, desc: "Una sombra que  va con vos", precio: 5.29, talle: "S", img: './img/20011777-04.png'},
    {id: 18, nombre: "sombras 6", tipo: "sombras", cantidad: 1, desc: "Una sombra que  va con vos", precio: 5.29, talle: "M", img: './img/20011777-01.png'},
    {id: 19, nombre: "brocha 1", tipo: "brocha", cantidad: 1, desc: "Una brocha que  va con vos", precio: 5.29, talle: "L", img: './img/brushes.jpg'},
    {id: 20, nombre: "brocha 2", tipo: "brocha", cantidad: 1, desc: "Una brocha que  va con vos", precio: 5.29, talle: "L", img: './img/brushes.jpg'},
    {id: 21, nombre: "brocha 3", tipo: "brocha", cantidad: 1, desc: "Una brocha que  va con vos", precio: 5.29, talle: "M", img: './img/brushes.jpg'},
    {id: 22, nombre: "brocha 4", tipo: "brocha", cantidad: 1, desc: "Una brocha que  va con vos", precio: 5.29, talle: "M", img: './img/brushes.jpg'},
    {id: 23, nombre: "brocha 5", tipo: "brocha", cantidad: 1, desc: "Una brocha que  va con vos", precio: 5.29, talle: "S", img: './img/brushes.jpg'},
    {id: 24, nombre: "brocha 6", tipo: "brocha", cantidad: 1, desc: "Una brocha que  va con vos", precio: 5.29, talle: "S", img: './img/brushes.jpg'},
]